version: '3'

services:
  #
  # WebService - microservice
  #
  webservice:
    build:
      context: ./WebService
      dockerfile: Dockerfile
    ports:
      - "4000:4000"

  #
  # WorkerService - microservice
  #
  workerservice:
    build:
      context: ./WorkerService
      dockerfile: Dockerfile
